spring:
  application:
    name: ssmu-api
  profiles:
    active: local
  datasource:
    url: jdbc:oracle:thin:@localhost:1522/xe
    username: system
    password: oracle
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /doc/swagger-ui.html
    enable: true
  api-docs:
    path: /api-docs
    enable: true

server:
  port: 8080
  servlet:
    context-path: /ssmu-api

logging:
  level:
    root: info