spring:
  application:
    name: sitas-api
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/sitas
    username: sitas
    password: sitas
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  swagger-ui:
    path: /doc/swagger-ui.html
    enable: true
  api-docs:
    path: /api-docs
    enable: true

server:
  port: 8080
  servlet:
    context-path: /sitas-api

logging:
  level:
    root: info

flyway:
  url: jdbc:mysql://localhost:3306/mysql
  schemas: sitas
  user: "sitas"
  password: "sitas"